export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const UPDATE_CART = 'UPDATE_CART';
export const GET_CART = 'GET_CART';
// export const CREATE_STREAM = 'CREATE_STREAM';
// export const FETCH_STREAMS = 'FETCH_STREAMS';
// export const FETCH_STREAM = 'FETCH_STREAM';
// export const DELETE_STREAM = 'DELETE_STREAM';
// export const EDIT_STREAM = 'EDIT_STREAM';
